var utils = require("mykoop-utils");
var routes = require("./routes");
var translations = require("../locales");
var endpoints = require("./endpoints");
var permissions = require("./permissions");
var adminEditPlugins = require("./adminEditPlugins");
var metaDataBuilder = new utils.MetaDataBuilder();
routes.addRoutes(metaDataBuilder);
metaDataBuilder.addData("translations", translations);
metaDataBuilder.addData("endpoints", endpoints);
metaDataBuilder.addData("permissions", permissions);
metaDataBuilder.addData("adminEditPlugins", adminEditPlugins);
var resMetaData = metaDataBuilder.get();
module.exports = resMetaData;
